### ISSUE TITLE
Remove API Key from source control

### ISSUE THREAD

**Issue by TravisNelsen** [blake-meyer/trading-bot#1]
https://github.com/blake-meyer/trading-bot/blob/60206e0d24c9b59b314facd0c291a510c77b702d/Program.cs#L15

Ideally you should have this in a config file that is ignored as a part of your .gitignore. I would set this repo back to private until you get it removed from commit history (even if it is a test API key)

**Comment by blake-meyer** [comment]
Thanks for mentioning this. This is a test key and also one of the first things I fixed in first-branch which includes the latest code. I'll create a PR and get the latest into main.

**Comment by blake-meyer** [comment]
Merged latest code and credentials are now stored in a secrets.json file which is not checked in. I've rotated the test keys and am okay with leaving public. Thanks for pointing it out!

**Comment by TravisNelsen** [comment]
Awesome, good stuff!
